### ISSUE TITLE
Map List

### ISSUE THREAD

**Issue by snixtho** [EvoEsports/EvoSC-sharp#133]
- ~~The map list shows the current available maps in the loaded match settings. It also shows which maps are queued to be played.~~ https://github.com/EvoEsports/EvoSC-sharp/issues/176
- ~~For the map list itself, it should display the name, author, rating/karma, and the player's local time.~~ https://github.com/EvoEsports/EvoSC-sharp/issues/176
- ~~It should also be possible to favorite certain maps and open more details about the map.~~ https://github.com/EvoEsports/EvoSC-sharp/issues/177
- ~~For moderators and admins, there should be an easy way to disable or delete the map.~~ https://github.com/EvoEsports/EvoSC-sharp/issues/176
- ~~The map list should be sortable by no finish, no local, best local/pb, karma/rating, the map name, author etc.~~ https://github.com/EvoEsports/EvoSC-sharp/issues/177
- ~~It should be possible for users to search specific map names and authors.~~ https://github.com/EvoEsports/EvoSC-sharp/issues/177
- ~~It should be possible to list all maps of an author.~~ https://github.com/EvoEsports/EvoSC-sharp/issues/177
- ~~There should be a tagging system on the maps, so that maps can be categorized into different tags, and these tags can be searched upon to only show maps with a certain tag.~~ https://github.com/EvoEsports/EvoSC-sharp/issues/177
- ~~For queued maps, it should have an easy way to drop it from the queue.~~ https://github.com/EvoEsports/EvoSC-sharp/issues/176

The layout of the maps are yet to be determined, whether its a table listing maps per row, column-based with cards, if it uses pagination or scrolling to navigate etc.

**Comment by DasNeo** [comment]
I've split this into three new issues:

1. https://github.com/EvoEsports/EvoSC-sharp/issues/175
2. https://github.com/EvoEsports/EvoSC-sharp/issues/176
3. https://github.com/EvoEsports/EvoSC-sharp/issues/177
