### ISSUE TITLE
MOTD Module

### ISSUE THREAD

**Issue by snixtho** [EvoEsports/EvoSC-sharp#141]
The MOTD (Message Of The Day) module will display a window with a customizable message to all players that join the server. Players can also chose to not show the current one again. If the MOTD is updated, it will show up again. It should also have the possibility to fetch the MOTD from an API so that we can remotely edit it.

Maybe also have a way to only display it to certain players.

The customizable message should allow formatting and possibly an in-game editor to edit it.

**Comment by DasNeo** [comment]
- [ ] Implement new Window (https://github.com/EvoEsports/EvoSC-sharp/issues/173)
- [ ] Change MotdEdit to use Form instead of TriggerPageAction as that has a limit
- [ ] Sanitize MotdEdit Text

**Comment by snixtho** [comment]
> * [ ]  Implement new Window ([Create set of visually consistent standard components with focus on usability, accessibility #173](https://github.com/EvoEsports/EvoSC-sharp/issues/173))

This is already done in the `173_reusable_ui_components` branch.
