### ISSUE TITLE
[BUG] Broken links in readme

### ISSUE THREAD

**Issue by snixtho** [evoesports/EvoSC-sharp#157]
The readme contains broken links as the name of the Github organization has changed. The documentation is also at a new place at https://evosc.io

**Comment by KhurramJalil** [comment]
Do you mind sharing the new link for Project Board which is currently pointing to the following broken link.

> https://github.com/orgs/EvoTM/projects/8

Additionally, you want the broken link in the following statement to point to https://evosc.io/ , right?

> We also have a documentation of the current code base available at https://evotm.github.io/EvoSC-sharp-documentation/

**Comment by snixtho** [comment]
At the top of the repository you can find the project board under the project tab. This would be the link: https://github.com/orgs/evoesports/projects/8

Amd yes, https://evosc.io/ would be the correct link :)

**Comment by KhurramJalil** [comment]
@snixtho Please review / approve the PR above.

**Comment by reaby** [comment]
I'll close the issue as completed. PR merged already.
