### ISSUE TITLE
Alternative mocking library for Moq

### ISSUE THREAD

**Issue by snixtho** [EvoEsports/EvoSC-sharp#190]
Due to recent changes in the Moq library, there are big privacy concerns, which are also violating GPDR. In short, Moq added the dependency "SponsorLink" (a closed source library) which harvests email addresses from git logs and sends them to a privately-owned cloud service. This is an automatic process that is injected and executed during build-time, and occurs without the developer's consent.

Moq is used extensively in our tests and because of this, we might need to look for alternative mocking libraries.

Some options right now are:
- Pin Moq at version 4.18.4 as it should not be affected
- Move to NSubstitute: https://nsubstitute.github.io/

Due to time constraints with XPEvo, it is currently not feasable to re-write all the tests until after the event. But I created this issue so that we can discuss what to do after XPEvo.

More information about the issue can be found here: https://github.com/moq/moq/issues/1372

We are open for any suggestions on alternatives or ideas on what to do.

**Comment by kdankert** [comment]
We should definetely pin the version as a quick fix and move to another framework after xpevo. https://github.com/moq/moq/issues/1372#issuecomment-1670948461 seems to restrict versions to only use versions below 4.20.

**Comment by snixtho** [comment]
Closing this as it is no longer a issue iirc.
