### ISSUE TITLE
[Feature] Toornament module

### ISSUE THREAD

**Issue by AtomicLiquid** [EvoEsports/EvoSC-sharp#262]
**Is your feature request related to a problem? Please describe.**
The toornament module should integrate with the Toornament API to both manually and automatically update the matches on Toornament.

**Describe the solution you'd like**
Must have's:
Initial setup through chat commands (ordered list of actions):
 * Starting the Toornament match within the game
 * Fetch match password
 * Set server name
 * Configure match settings and map order

Nice-to-have:
 * Whitelist players and spectators on the guest list
 * Automated initial setup (when match is up next)

**Describe alternatives you've considered**

**Additional context**

**Comment by snixtho** [comment]
Would like to discuss it's place as an internal module as it depends on a 3rd party service.

**Comment by Chris92de** [comment]
This should be a third-party module, not an internal one, similar to the Geardown module we had for last year's XPEvo.

**Comment by AtomicLiquid** [comment]
Could definitely be a third-party module, just using this as a means of tracking the feature.

**Comment by snixtho** [comment]
I will close this then to avoid polluting the list of issues not related to core of EvoSC#.
