### ISSUE TITLE
Redesign the Current Map Widget

### ISSUE THREAD

**Issue by snixtho** [EvoEsports/EvoSC-sharp#277]
I think this doesn't look that great and feels like just some text put into a rectangle. We should think of a better design for this.

![image](https://github.com/user-attachments/assets/bc42b2f9-4cce-488e-ae0c-de7a4fe5b540)

**Comment by Chris92de** [comment]
I prefer this design from the concept art/mockup you showed me.
![image](https://github.com/user-attachments/assets/18531539-af02-4ef8-84b0-098f2c7e9fb3)

**Comment by Chris92de** [comment]
Works quite well in TMNF in combination with the other widget styles (obviously not a 100% match with the EvoSC# widgets due to limited available fonts)
![image](https://github.com/user-attachments/assets/b0ae313b-a81f-493d-8824-7d122709ea77)

**Comment by araszka** [comment]
Looks like this now
![image](https://github.com/user-attachments/assets/ce52fde6-1cb8-4fa4-94d4-3508bfa15a4e)
