### ISSUE TITLE
/t Chat does not work

### ISSUE THREAD

**Issue by SupremeNotRacistIswear** [EvoEsports/EvoSC-sharp#283]
When playing the match i got a bit pissed, so i wanted to insult a teammate of mine.
Sadly it seems that the /t chat does not work.
even though it defaults to /t when u first try to send a message

Might be smart to fix it, some things are not for the public eye

**Comment by snixtho** [comment]
That is quite an interesting case for a bug report. But, this isn't a bug as it's simply a feature that is not implemented yet.

I do see the usefulness of this anyways in team matches when you want to communicate with the team without exposing tactics and such to the other.

**Comment by SupremeNotRacistIswear** [comment]
Then it might be useful to remove that feature all together untill its implemented? to assure there's no confusion.
just dont let it default to /t in chat before writing a message?

**Comment by snixtho** [comment]
> Then it might be useful to remove that feature all together untill its implemented? to assure there's no confusion. just dont let it default to /t in chat before writing a message?

Defaulting to /t is not part of EvoSC#, it is the game itself doing that and not something we can change.

**Comment by SupremeNotRacistIswear** [comment]
alright i did not know that.. 
that's actually still annoying but i do understand now.
